# Created on 2023-08-01

# @author: Roland

# @abstract: this Docker Compose file defines 3 services: a database
# service using a custom PostgreSQL image, an application service built from
# a local Dockerfile, and a Firefox/Selenium service for web automation.

version: '3.8'
services:
  db:   # This is the database service
    image: nyt-db  # image to be used for the 'db' service.
    volumes:  # Mount local direct. as a vol. attached inside the 'db' container
      - dbdata:/var/lib/postgresql/data 
    ports: # Port 5432 of 'db' container ass. with port 5433 on host machine
      - "5433:5432"  
    environment:  # Used to create a new database at container startup
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: nyt

  app:  # This is the application service
    image: nyt-app:data
    build:
      context: .  # Build context is the current directory
      dockerfile: Dockerfile.data  # Use this Dockerfile for building the image
    volumes:
      - .:/app  # Mount the application directory
    ports:
      - "8050:8050"
    environment:  # Environment variables for the application service
      YEAR: 2023
      MONTH: 1
      DAY: 9
    depends_on:  # This service depends on db and firefox services
      - db
      - firefox
    
  firefox:  # This is the firefox/selenium service for web scraping
    image: selenium/standalone-firefox  # Use the standalone Firefox image from Selenium
    ports:
      - "4444:4444"  # Expose the Selenium server port
      - "7900:7900"  # Expose the NoVNC web interface port

volumes:
  dbdata:
