# Use a parent image
FROM python:3.10-slim

# Set the working directory in the container to /app
WORKDIR /usr/src/app

# Copy the requirements.txt file into the container at /usr/src/app
COPY requirements.txt ./

# Install Python dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Copy the useful file into the container at /usr/src/app
COPY config.py ./
COPY src/ ./src/

# Set the main script as the container's entrypoint
CMD ["python", "./src/data_main/main.py"]
