apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: python-app
  template:
    metadata:
      labels:
        app: python-app
    spec:
      containers:
        - name: python-app
          image: dasycarpum/nyt-app-data:latest
          imagePullPolicy: Always
          env:
            - name: YEAR
              value: "2023"
            - name: MONTH
              value: "1"
            - name: DAY
              value: "9"
          ports:
            - containerPort: 8050

---

apiVersion: v1
kind: Service
metadata:
  name: python-app-service
spec:
  type: LoadBalancer
  ports:
  - port: 8050
    targetPort: 8050
  selector:
    app: python-app

