# Created on 2023-09-10

# @author: Roland

# @abstract: this Docker Compose file defines 2 services: a database
# service using a custom PostgreSQL image and an application service, for 
# expose SQL query code as an API, built from a local Dockerfile

version: '3.8'
services:
  db:  # This is the database service
    image: nyt-dump # image to be used for the 'db' service.
    volumes:  # Mount local direct. as a vol. attached inside the 'db' container
      - dbdata:/var/lib/postgresql/data
    ports: # Port 5432 of 'db' container ass. with port 5434 on host machine
      - "5434:5432" 
    environment: # Used to create a new database at container startup
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: nyt

  app: # This is the application service
    image: nyt-app-api
    build:
      context: ../  # Build context is the current directory
      dockerfile: pipeline/Dockerfile.api # Use this Dockerfile for building the image
    volumes: 
      - .:/usr/src/app # Mount the application directory
    ports:  
      - "8000:8000" # FastAPI default port
    depends_on: # This service depends on db service
      - db

volumes:
  dbdata:
