apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: python-app
  template:
    metadata:
      labels:
        app: python-app
    spec:
      containers:
        - name: python-app
          image: dasycarpum/nyt-app-api
          imagePullPolicy: Always
          env:
          - name: DB_PASS
            valueFrom:
              secretKeyRef:
                name: my-secret
                key: DB_PASS
          ports:
            - containerPort: 8000

---

apiVersion: v1
kind: Service
metadata:
  name: python-app-service
spec:
  type: LoadBalancer
  ports:
  - port: 8000
    targetPort: 8000
  selector:
    app: python-app

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: my-app-ingress
spec:
  defaultBackend:
    service:
      name: python-app-service
      port:
        number: 8000
