apiVersion: apps/v1
kind: Deployment
metadata:
  name: firefox-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: firefox
  template:
    metadata:
      labels:
        app: firefox
    spec:
      containers:
        - name: firefox
          image: selenium/standalone-firefox
          imagePullPolicy: Always
          ports:
            - containerPort: 4444
          
---

apiVersion: v1
kind: Service
metadata:
  name: firefox-service
spec:
  ports:
  - port: 4444
  clusterIP: None
  selector:
   app: firefox
